# Generated by Django 3.1 on 2021-01-13 19:50

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attending',
            new_name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
