# Generated by Django 3.1 on 2021-03-13 00:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0002_auto_20210308_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='id',
            field=models.CharField(db_index=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 3, 13, 0, 34, 11, 755367, tzinfo=utc), max_length=250, unique=True),
        ),
    ]
