# Generated by Django 3.1 on 2020-12-22 23:14

import django.contrib.auth.models
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201222_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='photos/default-user-avatar.png', upload_to='photos/', verbose_name='Photo'),
        ),
    ]
