# Generated by Django 3.1 on 2021-03-08 20:49

import apps.checklist_items.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.CharField(db_index=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=apps.checklist_items.models.get_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.checklist')),
            ],
        ),
    ]
