# Generated by Django 3.1 on 2020-11-25 20:33

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20201118_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='classification',
            field=models.CharField(choices=[('work', 'Work'), ('pleasure', 'Pleasure'), ('both', 'Both'), ('none', 'None')], max_length=35),
        )
    ]
