# Generated by Django 3.1 on 2020-12-01 22:05

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20201125_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
