# Generated by Django 3.1 on 2020-12-16 00:20

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20201201_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripMember',
        ),
    ]
