# Generated by Django 3.1 on 2021-01-26 23:53

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('trips', '0005_auto_20201215_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='location.location'),
        ),
    ]
